### PR TITLE
Fix lock page calculation

### LINKED ISSUE #114: Wrong $veNATION calculation on /lock page
When the lock is an extension of a pre-existing lock, the final balance estimation fails:

image

https://app.nation3.org/lock

### PR DESCRIPTION
**Pull request by biendeveloper**
## Dework Task
https://app.dework.xyz/nation3/app-2?taskId=c76a4e30-ca38-4c25-bce1-fc21fb172254

## Related GitHub Issue
Fixes #114 

image

### CODE REVIEW

**Comment by aahna-ashina** [comment]
@biendeveloper A major refactoring PR was just merged into main:  https://github.com/nation3/app/pull/103

So please fetch upstream changes, and update your branch 😄

**Review by aahna-ashina — APPROVED** [review]

File: ui/pages/lock.tsx [hunk 1]
```diff
@@ -416,11 +416,7 @@ export default function Lock() {
                           NumberType.number
                         ),
                         time: Date.parse(lockTime.formatted),
-                        lockTime: Date.parse(
-                          hasLock && lockTime?.orig
-                            ? lockTime.orig.formatted
-                            : new Date()
-                        ),
+                        lockTime: Date.parse(new Date().toString()),
```
Comment (johnmark13) [inline ui/pages/lock.tsx:419]: I really like how much more simple this is, is this the agreed logic that the new lock is considered as being taken from today and the initial lock date is "forgotten"?

Comment (aahna-ashina) [reply ui/pages/lock.tsx:419]: @johnmark13 Yes:  https://discord.com/channels/690584551239581708/1006193778345914378/1021708067211055154

**Review by johnmark13 — APPROVED** [review]
